CREATE DATABASE SP;
USE SP;
CREATE TABLE STU(
rollno INT PRIMARY KEY,
name VARCHAR(50),
marks INT NOT NULL,
grade VARCHAR(1),
city VARCHAR(10)


);
INSERT INTO STU
(rollno,NAME,marks,grade,city)
VALUES
(21,"ROHIT",45,"c","kolkata"),
(22,"SUBHAM",71,"b","delhi"),
(23,"ARITRA",90,"a","pune"),
(24,"riju",80,"a","durgapur"),
(25,"laxmi",55,"b","faridabad"),
(26,"tarun",70,"b","mumbai");
/*LIMIT CLAUSE*/
SELECT * FROM SAHIL
WHERE MARKS < 95
 LIMIT 3;
 /*ASSCENDING ORDER(ASC)*/
 SELECT * FROM SAHIL ORDER BY MARKS ASC;
  /*DESCENDING ORDER(DESC)*/
  SELECT * FROM SAHIL ORDER BY MARKS DESC LIMIT 2;
   /* MARKS CALCULATE*/
SELECT MAX(MARKS)FROM SAHIL;
SELECT SUM(MARKS)FROM SAHIL;
SELECT CITY,COUNT(ROLLNO)
FROM SAHIL GROUP BY CITY;
SELECT CITY, AVG(MARKS)
FROM SAHIL GROUP BY CITY ORDER BY CITY ASC;  


SELECT GRADE,COUNT(NAME)
 FROM SAHIL
GROUP BY GRADE
ORDER BY GRADE;

SELECT CITY,COUNT(NAME)
FROM SAHIL
GROUP BY CITY
HAVING MAX(MARKS) < 90;
CREATE TABLE PP(
NAME VARCHAR(50),
AGE INT PRIMARY KEY,
SALARY INT

);
INSERT INTO PP
(NAME,AGE,SALARY)
VALUES
("SAHIL",22,25000),
("ROHIT",25,22000),
("RIJU",26,45000);

 SELECT * FROM PP;
  CREATE TABLE TEMP3(
  ID INT UNIQUE
  ); 
  
  INSERT INTO TEMP3 VALUES("202"); 
   
SELECT * FROM TEMP3;
DROP TABLE TEMP3;
CREATE TABLE SO(
ID INT NOT NULL
);
INSERT INTO SO VALUES("239");

INSERT INTO SO VALUES("239");
DROP TABLE SO;
SELECT CITY
FROM SA
WHERE GRADE = "A"
GROUP BY CITY
HAVING MAX(MARKS)>75
ORDER BY CITY ASC;
UPDATE SA 
SET MARKS = MARKS + 5
WHERE MARKS BETWEEN 45 AND 90;
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM SA;

DELETE FROM SA 
WHERE MARKS < 80;
SELECT * FROM SA;
/*FOREIGN KEY*/ 
CREATE TABLE DEPT(
ID INT PRIMARY KEY,
NAME VARCHAR (50)
);
INSERT INTO DEPT VALUES 
(104,"BENGALI"),
(105,"HINDI");

 
UPDATE DEPT
SET ID = 109
WHERE ID = 104;
CREATE TABLE TEACHER(
ID INT PRIMARY KEY,
NAME VARCHAR (50),
DEPT_ID INT ,
FOREIGN KEY (DEPT_ID) REFERENCES DEPT (ID) 
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO TEACHER VALUES
(102,"PAUL",104),
(103,"DEY",105);
SELECT * FROM TEACHER;
ALTER TABLE S
RENAME TO STU;
TRUNCATE TABLE STU;
SELECT * FROM STU;
ALTER TABLE STU 
CHANGE NAME FULL_NAME VARCHAR (50);
DELETE FROM STU
WHERE MARKS < 80;
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE STU
DROP COLUMN GRADE;


CREATE TABLE STUDENT(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(50)


);
INSERT INTO STUDENT VALUES (101,"ADAM"),(102,"JACK"),(103,"BOB");
SELECT * FROM STUDENT;
CREATE TABLE SUBJECT(
STUDENT_ID INT PRIMARY KEY,
SUJECT VARCHAR (100)
);
INSERT INTO SUBJECT VALUES (102,"COMPUTER ORGANIZATION"),(104,"PYTHON"),(103,"DATA STRUCTURE"),(108,"BIOLOGY");
SELECT * FROM SUBJECT;
SELECT * FROM STUDENT
LEFT JOIN SUBJECT
ON STUDENT.STUDENT_ID = SUBJECT.STUDENT_ID;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;

SELECT * FROM STUDENT
LEFT JOIN SUBJECT
ON STUDENT.STUDENT_ID = SUBJECT.STUDENT_ID
UNION
SELECT * FROM STUDENT
RIGHT JOIN SUBJECT
ON STUDENT.STUDENT_ID = SUBJECT.STUDENT_ID
WHERE STUDENT.STUDENT_ID IS NULL
OR 
SUBJECT.STUDENT_ID IS NULL;






